### ISSUE TITLE
Suggestion or FR ( Upgrade this for LV 5.3 ? )

### ISSUE THREAD

**Issue by DavidStrada** [jimfrenette/laravel-vuejs-jwt-auth#1]
I have been trying to make this work on LV 5.3 but there's some many nuances, have you tried to doit? or would you doit ? 

thanks!

**Comment by jimfrenette** [comment]
I have not done much with 5.3 aside from simply installing it locally. For one my web host does not support PHP >= 5.6.4 - so I am in no rush.

Have you looked at the new Passport API Authentication that is included with 5.3?
https://laravel.com/docs/5.3/passport

**Comment by DavidStrada** [comment]
Yeah I 've looked over "Passport" I guess i should check it out, just wondering if you had plans to upgrade your tut, but thanks for your input!
