### ISSUE TITLE
ready() not work

### ISSUE THREAD

**Issue by Bebbolus** [jimfrenette/laravel-vuejs-jwt-auth#4]
With Vue2, you need mounted() instead of ready() on laravel-vuejs-jwt-auth/resources/assets/components/App.vue

**Comment by jimfrenette** [comment]
Testing this. When the app was converted for Vue 2 a couple months ago, the [migration helper](https://github.com/vuejs/vue-migration-helper ) did not catch it.
https://vuejs.org/v2/guide/migration.html#ready-replaced

**Comment by jimfrenette** [comment]
[tag 2.1](https://github.com/jimfrenette/laravel-vuejs-jwt-auth/tree/2.1) and master as of commit [0b0769e](https://github.com/jimfrenette/laravel-vuejs-jwt-auth/commit/0b0769e53ea3525fe575efa788f5ffd3d5c51ee4) use mounted instead of ready in App.vue component
