### ISSUE TITLE
Vue.internalDirectives.component Error for Branch 1.0

### ISSUE THREAD

**Issue by brickgale** [jimfrenette/laravel-vuejs-jwt-auth#5]
![error](https://cloud.githubusercontent.com/assets/6366161/22418812/74a3fc00-e68f-11e6-86e4-b7d84962b869.png)

**Comment by brickgale** [comment]
Is it because of the VueRouter? since I eliminated VueRouter(only left VueResource) on code, there is no error.

**Comment by brickgale** [comment]
Fixed. I didn't know it is possible once you install first a vue directive like (vue-material), it will automatically set vue.js (the wrong version - 2.1) to be fetched on require. Solved it when I deleted node_modules, then npm install and to be safe I put the vue.js on devDependencies correct version.

**Comment by jimfrenette** [comment]
Thanks for the info - I'm going to look into tighter dependency version specification for the package.json npm manifest per https://docs.npmjs.com/files/package.json#dependencies
